### ISSUE TITLE
request to agree how the miner-wallet interaction works

### ISSUE THREAD

**Issue by johnog65536** [johnog65536/Currency#5]
@domgoodwin I think we need to agree a couple of interactions - today if possible. Sorry if already done, had head down in a bid for most of the last week and now stressing over tuesday!

1. How do we get certain private keys out of the blockchain / miner? I need these available in the wallet somehow, so the wallets can then spend the cash.  
- priv key for the genesis node
- priv key for the coins a miner claims for generating a block

Or perhaps, given you shouldn't really be able to extract those, perhaps there should be a command line argument (password) when instantiating the miner. On instantiation, the first miner does not create the geneses block, but waits for a wallet to make a initialisation call from a wallet which provides the priv key for the genesys block, and can only be called once, and needs that password. Another method requiring the password can be called to set the key the miner sends mined coins / transaction fees to. That method can be called as many times as you like.  
**What do you think?**

2. When spending the cash we need to confirm the spend API the miner exposes
- the send transaction spec, something like 
- - <inputs array of> previous txn ID, prev output index, privKey signature of that output's pubkey
- - <outputs array of> index, value, pubkey
- - (optional?) confirmation fee
- - output param containing the transaction ID
- get transaction method returning everything about a transaction (input array, output, etc)
- check confirmed method to see if a transaction ID made it onto the chain yet
- check spent method to see if a transaction id + output index has been spent yet
- get value method to return the value for an transaction id + output index
- get balance method for a given key & which analyses the entire blockchain to return the bal

3. for availability / performance, when a transaction gets confirmed, should we stamp it with the block ID too, so that later when we try to spend it, the find transaction method takes the block id, and the txn ID

**Comment by domgoodwin** [comment]
1. Since this is a basic blockchain we're created now I think the best thing to do is an API which allows you to register a wallet, this will give you a single key pair, private is returned, public is stored on the miner. Do a call to the register api and it will store your pub key, creating your 'wallet'. Currently the chain is identified by it's name and the server has that hard coded (server.js).

2. One of my TODOs is the transaction confirmations, my plan is when you create a transaction it checks you have the funds then stores it as a pending transaction (in a local pending_tx.json file), once the confirm is called (either every X mins or manually) those are added to the chain one by one, checked before they are. I'm thinking leave out confirmation 'fees' for now just for simplicity and it's more of something to add when we take this distributed. 
I think the miner can handle the confirmations internally, the client just creates a transaction which goes from requested->pending->confirmed on the chain, available to retrieve using the tx id.
Balance is a weird one, I think the best thing is the client works it out from the retrieved full chain, goes through previous transactions and calculates it.

3. Transactions will be stamped with block id when they move from pending>confirmed

I'll work on these tomorrow, but any questions let me know.

**Comment by johnog65536** [comment]
Have added to TestHttpCallOnMiner a registerGenesysKeysPost() method - passing in the keys for the genesys transaction, and an initial createTransaction() method passing in spend transactions, hanging off that initial genesys txn

Latter isnt quite finished, I need a way to get the outouts from a transaction back so I can feed them into the above s

**Comment by johnog65536** [comment]
Should add: the JSON in the above 2 methods is an initial punt - happy to change it!

**Comment by domgoodwin** [comment]
For the create transaction here an example of the body (JSON format) which will create the transaction:
`{"amount":"10","fromAddress":"fromAddr","toAddress":"toAddr","comment":"hello world"}`

I'm just adding the pending->confirmed logic then I'll push that up into a new branch

**Comment by johnog65536** [comment]
will go with above structure in next iteration. Gives us enough to demo

Think we need to revisit it at somepoint to add validation of signatures (priv key requriement), and I thought bitcoin worked on the principle of having to spend a previous output?

**Comment by johnog65536** [comment]
TestHttpCallOnMiner.createSimpleTransaction() added which pushes up a transaction in this form
HTTP Post to: http://localhost:8080/api/create
Example POST body contents (let me know if you want the : "requestjson=" removing):
`requestjson={"amount":5.0,"fromAddress":"MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMzYRZpH/eXiF6k0E/RwgE41T6zhMD6U531AONuK39UHzGtpzBOHaI1uHNccuuH3PTxNsmHvzhH1c76n0qZ/NXsCAwEAAQ\u003d\u003d","toAddress":"MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIJNdAOTgHMglaZtMO1S3CZ/QCXvR8EqyOaUzl35dhu3lNo+9Xlx6/8omlEobFLS4HLdKZtpNI0atpqL1vBUqIMCAwEAAQ\u003d\u003d","comment":"Pay form the genesis key to my first key!"}`

Both addresses are public keys, saved in UTF8 then Base 64 encoded.
I have had lots of fun with encoding! For reference, I use this code to get the base 64 encoded string
```
	public String getPubKeyAsString() {
		byte[] encodedKey= keypair.getPublic().getEncoded();
		String base64Encoded = CryptoUtils.utfToBase64(encodedKey);
		return base64Encoded;
	}
```


I am using this code: 
```
	public static PublicKey generatePubKey (String inputString) throws UnsupportedEncodingException, NoSuchAlgorithmException, InvalidKeySpecException {
		byte[] encodedByteKey = getBytes(inputString);
		byte[] byteKey=Base64ToUTF(encodedByteKey);
		X509EncodedKeySpec X509publicKey = new X509EncodedKeySpec(byteKey); 
		KeyFactory kf = KeyFactory.getInstance(KEY_TYPE); 
		
		return kf.generatePublic(X509publicKey);  		
	}
```

To convert the encoded string back to a Public Key
